/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/example-a/a.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    ItemBase: typeof import('./src/components/ItemBase.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    Playground: typeof import('./src/components/playground/index.vue')['default']
    ResultItem: typeof import('./src/components/ResultItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    YButton: typeof import('yalert-ui')['YButton']
    YRow: typeof import('yalert-ui')['YRow']
  }
}
