/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBtns: typeof import('./src/components/home/ActionBtns.vue')['default']
    Clock: typeof import('./src/components/home/Clock.vue')['default']
    Divider: typeof import('./src/components/app/Divider.vue')['default']
    Drawer: typeof import('./src/components/nav/Drawer.vue')['default']
    Example: typeof import('./src/components/examples/Example.vue')['default']
    ExampleMissing: typeof import('./src/components/examples/ExampleMissing.vue')['default']
    Figure: typeof import('./src/components/app/Figure.vue')['default']
    Flat: typeof import('./src/components/home/Flat.vue')['default']
    Footer: typeof import('./src/components/home/Footer.vue')['default']
    Head: typeof import('./src/components/home/head.vue')['default']
    Heading: typeof import('./src/components/app/Heading.vue')['default']
    Headline: typeof import('./src/components/app/Headline.vue')['default']
    Img: typeof import('./src/components/app/Img.vue')['default']
    Link: typeof import('./src/components/app/Link.vue')['default']
    List: typeof import('./src/components/app/List.vue')['default']
    Markup: typeof import('./src/components/app/Markup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./src/components/app/Sheet.vue')['default']
    Table: typeof import('./src/components/app/Table.vue')['default']
    TeamMember: typeof import('./src/components/about/TeamMember.vue')['default']
    Title: typeof import('./src/components/app/Title.vue')['default']
    Toc: typeof import('./src/components/app/Toc.vue')['default']
    Usage: typeof import('./src/components/examples/Usage.vue')['default']
    UsageExample: typeof import('./src/components/examples/UsageExample.vue')['default']
    VueFile: typeof import('./src/components/examples/VueFile.vue')['default']
  }
}
